### ISSUE TITLE
Multi-platform support

### ISSUE THREAD

**Issue by kesne** [kesne/jeopardy-bot#133]
Refactor things so that we can support multiple chat platforms. If we remove multi-mode support, then we can just made the only feature toggle the platform.
- Discord (https://github.com/hydrabolt/discord.js/)
- Hipchat (https://github.com/cjoudrey/wobot)

**Comment by pstephenson02** [comment]
Hi @kesne! I met you at the Airbnb hackathon a few weeks ago (Phil). You helped me get this app set up and we talked a bit about how to integrate Hipchat (my company uses hipchat, and my coworkers would love this thing). I'm not really a javascript developer, so this has been a challenge for me to say the least. It looks like you've been busy working on this thing -- I noticed quite a few changes since the last time I pulled down master.

With respect to hipchat integration, I have a branch started: https://github.com/kesne/jeopardy-bot/compare/master...pstephenson02:hipchat

This took me quite a while just to get this much, but I know it still needs work. One thing to note: The bot that you listed above, wobot, is pretty old and was built for Hipchat's v1 api. Atlassian is building out this new platform they call Atlassian connect to try to provide a more friendly interface for "integrations". So they have a v2 api now. What's annoying about Atlassian though is they use Bitbucket, not Github :-1:. Their bitbucket repos are not very old, and hence aren't very SEO friendly. It took some searching, but Atlassian itself is actually building out some hipchat clients here:

https://bitbucket.org/atlassianlabs/atlassian-connect-express-hipchat

and there is another one for koa apps.

If you have any advice on how to best continue the integration, I'm all ears. The configuration definitely needs to be sorted out. Mostly I am just trying to get the thing working. I would love to continue working on this app and learn some more about express and node (I've learned a lot already), but I need a working app first!

Thanks in advance

**Comment by kesne** [comment]
@pstephenson02 So I've done a little bit of work lately to help make this possible. First of all, everything that communicates with Slack is now down to one class (https://github.com/kesne/jeopardy-bot/blob/master/src/slackbot.js). Essentially, if you just implement a class that does something similar (and contains a `broadcast` method), you should be able to make it work without having to re-work too much.

There are still assumptions on things like `apiKey` in the app model, but we can work those out. I'll work on getting a scaffold branch against master that adds the new options in the admin panel and will work for letting you test the new integration.

Unfortunately, it looks like the new API is really weird. There's this: https://github.com/charltoons/hipchatter but it looks like it doesn't support emitting an event when a new message is received.

**Comment by kesne** [comment]
I think it might be worth just using a node XMPP client to handle everything, because that works with Hipchat. Thoughts?

**Comment by pstephenson02** [comment]
This hipchatter module looks like it could work, and would be simpler than the scaffolding that these atlassian-connect modules want you to setup. For events, I think we could use the [create_webhook](https://github.com/charltoons/hipchatter#hipchattercreate_webhook) that will respond to room messages, notifications and channel joins, etc.

My only concern with using an XMPP client is that it seems like Atlassian isn't really maintaining or developing that interface anymore. Even the [documentation](https://ecosystem.atlassian.net/wiki/display/HCDEV/HipChat+XMPP+Protocol+Documentation) says: "This documentation is a mostly accurate reflection of the current state of the XMPP extensions used by HipChat and is subject to change dramatically without notice." - whatever that means.

I'll give this hipchatter module a try and see how it goes. Certainly willing to re-evaluate if needed.

**Comment by kesne** [comment]
Yeah let me know how that works out. I know the XMPP stuff isn't really supported, but it just looks preferable from an API perspective. If you can get the hipchatter module working though that'd be awesome. If you do use the `create_webhook` call, you'll also probably want to store that in memory and then use `get_webhook` to prevent creating a ton of webhooks. Assuming that it works the way I think it does, at least.

**Comment by kesne** [comment]
Something we'll probably also need here is formatter method that's passed to Trebek so that we can format usernames. For example, on Slack, it's `<@userid>`, but for discord.js, it's just `@username`.

**Comment by pstephenson02** [comment]
I've been testing out the hipchatter module and it seems to work just fine. It also takes an API key in its constructor, so maybe worth keeping that field in the admin dashboard even for Hipchat. The way that the Hipchat webhook api works is that when you register a webhook, it stores it server side and then when it fires, it will respond to any and all connected clients to that channel. I was able to register a webhook for all room_messages so it essentially acts as a listener and then posts to whatever url/route you have configured in the webhook. Because they're stored server side, I think we'll have to save some metadata like the webhook id and the url so that when the app fires up, it first checks whether those webhooks are already registered on the channel.

One difference between the slack and the hipchat api is this ['subtype'](https://api.slack.com/events/message) property on the messages. I noticed that in the slack class, you pass this along into the [trebek](https://github.com/kesne/jeopardy-bot/blob/master/src/slackbot.js#L103) module and then eventually onto the Command class. But I don't really understand what's going on after that in the Command constructor with this processWhens function. What do 'whens' represent? What do I need to use to call trebek for this?

Here is what the webhook response looks like:

``` json
{
    "event": "room_message",
    "item": {
        "message": {
            "date": "2016-01-12T04:04:11.043995+00:00",
            "from": {
                "id": 515616,
                "links": {
                    "self": "https://api.hipchat.com/v2/user/515616"
                },
                "mention_name": "Phil",
                "name": "Phil",
                "version": "00000000"
            },
            "id": "3822cc96-db14-4668-99c9-0bc7fce3b318",
            "mentions": [],
            "message": "test",
            "type": "message"
        },
        "room": {
            "id": 2231155,
            "is_archived": false,
            "links": {
                "members": "https://api.hipchat.com/v2/room/2231155/member",
                "participants": "https://api.hipchat.com/v2/room/2231155/participant",
                "self": "https://api.hipchat.com/v2/room/2231155",
                "webhooks": "https://api.hipchat.com/v2/room/2231155/webhook"
            },
            "name": "Jeopardy",
            "privacy": "private",
            "version": "323A5129"
        }
    },
    "webhook_id": 3472788
}
```

So as far as calling trebek, I've got `text, channel_name, channel_id, timestamp` (this might need a formatter as well, along with the user as you mentioned above), `user_id, user_name`:

```
    trebek(text, {
      subtype,
      channel_name: channelName,
      channel_id: channelId,
      timestamp,
      user_id: userId,
      user_name: userName,
    }, say);
```

**Comment by kesne** [comment]
@pstephenson02 Awesome work! 

The idea behind `whens` is that they're like triggers, but for channel events. Basically the only use for them right now is for the `channel_join` event, where we will greet users that join the channel. You could likely create a `room_enter` webhook for that case, and then just call the trebek module with that subtype after that happens.

Calling trebek looks correct. I think that what I'll probably do is make trebek a constructor that takes a message formatter for @-mentions, and then you can call it the same way it is called now. Another option would just be to add another function (similar to the say function) that you pass with every invocation.

In a perfect world, you'd be able to construct Trebek with the say method, but I couldn't figure out a good way to do that sadly. :(
