### ISSUE TITLE
Passing?

### ISSUE THREAD

**Issue by fwenzel** [kesne/jeopardy-bot#97]
Sometimes when you play alone or in a very small group you might want to pass rather than let the timer run out.

Is that a good idea? Does it keep others from jumping in?

**Comment by fwenzel** [comment]
If all current players pass it could reduce the remaining waiting time to 5 seconds (or so). We might want to combine that with the ability to "buzz" so someone can in fact interrupt.

**Comment by fwenzel** [comment]
Buzzing would be #28

**Comment by kesne** [comment]
This + buzzing makes sense. But buzzing is kind of controversial, and will probably be disable-by-default. but I think when all active users (users that have answered once in the round) have answered, it would make sense to drop the timeout.

The implementation of that would be tricky, but doable.

**Comment by kesne** [comment]
Over the last couple months, I've watched how these games generally progress, and I don't think I'll be implementing buzzers because it seems to kind of go against how the game is played (i.e. part of the fun is typing fast).

With no buzzers, I think the most sane thing we could do here is to half whatever the timeout is when everybody actively playing passes.

That said, I think that's solving an issue we should have (games progressing too slowly). I honestly think a better solution would be implementing per-room leaderboards (#139), and allowing private gameplay (either in DMs, DM groups, or private channels). Then, we could add a simple check to dump the timeout altogether if everybody in the channel/dm/group has already guessed. Then we don't have to have any complicated timeout logic, we just cancel a timeout and run the function immediately.

Plus, with the new admin console, we can tweak all of the timeout values per-room, so if you need faster play, there's another way to do that.
